### Connexion
POST http://localhost/connexion
Content-Type: application/x-www-form-urlencoded

email=dascotte.yann@uphf.fr&password=password

###

### Récupérer les absences sans filtres
GET http://localhost/api/absences

### Test avec des filtres pour un étudiant
GET http://localhost/api/absences?state=Refused&dateStart=2026-01-01&dateEnd=2026-01-07

### Déconnexion
POST http://localhost/deconnexion

### Connexion en tant que RP
POST http://localhost/connexion
Content-Type: application/x-www-form-urlencoded

email=kevin.masmejean@uphf.fr&password=password

### Test de récupération des absences d'un étudiant spécifique pour le RP
GET http://localhost/api/absences?idStudent=2