### Login a un compte RP
POST http://localhost/connexion
Content-Type: application/x-www-form-urlencoded

email=kevin.masmejean@uphf.fr&password=password

### Activer toutes les notifications
PUT http://localhost/api/mailAlert
Content-Type: application/json

{
  "mailAlertTeacher": true,
  "mailAlertEducationalManager": true
}

### Désactiver toutes les notifications
PUT http://localhost/api/mailAlert
Content-Type: application/json

{
  "mailAlertTeacher": false,
  "mailAlertEducationalManager": false
}

### Activer uniquement les notifications du prof
PUT http://localhost/api/mailAlert
Content-Type: application/json

{
  "mailAlertTeacher": true,
  "mailAlertEducationalManager": false
}

### Activer uniquement les notifications du rp
PUT http://localhost/api/mailAlert
Content-Type: application/json

{
  "mailAlertTeacher": false,
  "mailAlertEducationalManager": true
}

### Mauvais format 1
PUT http://localhost/api/mailAlert
Content-Type: application/json

{
  "mailAlertTeacher": false
}

### Mauvais format 2
PUT http://localhost/api/mailAlert
Content-Type: application/json

{
  "mailAlertEducationalManager": true
}

### Ne rien envoyer
PUT http://localhost/api/mailAlert
Content-Type: application/json

{}

### Deconnexion
GET http://localhost/deconnexion

### Compte professeur
POST http://localhost/connexion
Content-Type: application/x-www-form-urlencoded

email=vansteenkiste.dimitri19@gmail.com&password=password

### Activer mailAlertTeacher pour un prof
PUT http://localhost/api/mailAlert
Content-Type: application/json

{
  "mailAlertTeacher": true
}